const response = fetch("http://127.0.0.1:5000/api/rag/", {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
    },
    body: JSON.stringify({
        content: `
        # Customer Support Policy

## 1. Purpose

Our Customer Support Policy explains how we provide assistance to customers using our e-commerce platform. Our goal is to provide clear, timely, and helpful support throughout the customer journey, including product searches, orders, payments, delivery, returns, refunds, and general enquiries.

Our website also provides an AI-powered chatbot to offer quick assistance and help customers find relevant information.

## 2. AI Chatbot Support

Our AI chatbot is available to assist customers with common questions and tasks, including:

* Searching for products.
* Providing product information and recommendations.
* Answering frequently asked questions.
* Providing general information about orders and delivery.
* Explaining return and refund procedures.
* Helping customers navigate the website.
* Providing basic customer support information.

The chatbot is designed to provide quick and convenient assistance; however, AI-generated responses may occasionally be incomplete or inaccurate.

Customers should review important information before making purchasing or financial decisions.

## 3. Human Support

The AI chatbot is intended to support, rather than completely replace, human customer service.

If the chatbot cannot answer a customer's question or the issue requires further investigation, the customer may request assistance from the customer support team.

Human support may be required for issues such as:

* Incorrect or missing orders.
* Payment problems.
* Refund disputes.
* Account-related issues.
* Damaged or defective products.
* Complaints.
* Sensitive or complex customer enquiries.

Where appropriate, the chatbot will advise the customer to contact the support team.

## 4. Support Availability

The AI chatbot may be available 24 hours a day, subject to system availability and maintenance.

Human customer support enquiries will normally be reviewed during our standard support hours.

We aim to acknowledge customer enquiries within **24 hours** and provide a resolution or further update within **1–3 business days**, depending on the complexity of the issue.

Some enquiries involving delivery companies, payment providers, suppliers, or other third parties may require additional time.

## 5. Product Information and Recommendations

The AI chatbot may provide product suggestions based on the customer's search terms, preferences, and available product information.

Recommendations generated by the chatbot are provided to help customers discover relevant products and do not guarantee that a particular product will meet every customer's individual requirements.

Product prices, availability, descriptions, promotions, and delivery information may change. Customers should check the product page and checkout information before completing an order.

## 6. Order Support

Customers may contact customer support regarding:

* Order confirmation.
* Order status.
* Delivery information.
* Missing items.
* Incorrect products.
* Damaged products.
* Order cancellation.
* Returns and refunds.

Customers may be asked to provide their order number or other relevant information so that the support team can investigate the enquiry.

Customers should not provide passwords, full payment card details, PIN numbers, or other highly sensitive information to the AI chatbot.

## 7. Returns and Refunds

Customers wishing to return an item or request a refund should follow the return and refund procedures displayed on our website.

Eligibility for returns and refunds may depend on:

* The type of product.
* The condition of the product.
* The reason for the return.
* The date of purchase.
* Applicable consumer rights and our return conditions.

The AI chatbot may explain the return process but does not make the final decision regarding disputed refunds or exceptional return requests.

Complex cases may be reviewed by a member of the customer support team.

## 8. Complaints

We aim to resolve customer complaints fairly and professionally.

Customers may submit a complaint through the available customer support contact method on our website.

When submitting a complaint, customers should provide sufficient information about the issue, including relevant order details where applicable.

We will review the complaint and aim to provide a response within a reasonable period.

If further investigation is required, the customer will be informed.

## 9. AI Limitations

Although our AI chatbot is designed to provide useful and accurate assistance, customers should understand that:

* AI responses may occasionally contain errors.
* The chatbot may misunderstand a question.
* Product availability and prices may change.
* The chatbot may not have sufficient information to resolve complex cases.
* Some enquiries must be handled by human customer support.

If customers believe that the chatbot has provided incorrect information, they should contact customer support for clarification.

## 10. Customer Privacy

Customer privacy is important to us.

Information provided through the chatbot or customer support channels will only be used where necessary to provide support, improve our services, maintain security, or fulfil other legitimate operational requirements.

Customers should avoid entering unnecessary sensitive information into the chatbot.

Personal information will be handled in accordance with our Privacy Policy and applicable data protection requirements.

## 11. Appropriate Use of Customer Support

Customers are expected to use customer support services appropriately.

We may restrict access to support services where customers:

* Send abusive, threatening, or discriminatory messages.
* Attempt to misuse the chatbot or website.
* Attempt to obtain unauthorised access to accounts or systems.
* Submit deliberately false information.
* Use automated systems to disrupt customer support services.

We will continue to make reasonable efforts to assist customers while maintaining a safe environment for customers and support staff.

## 12. Service Availability

We aim to keep our chatbot and customer support services available whenever reasonably possible.

However, temporary interruptions may occur because of:

* Scheduled maintenance.
* Technical problems.
* Internet or hosting outages.
* Third-party service failures.
* Security incidents.

Where possible, services will be restored as quickly as reasonably practicable.

## 13. Improving Our Customer Support

We may review chatbot conversations, customer feedback, support requests, and service performance to identify opportunities to improve our customer support experience.

Where customer interaction data is used for evaluation or service improvement, it will be handled in accordance with our Privacy Policy and applicable data protection requirements.

## 14. Contacting Customer Support

If the AI chatbot cannot resolve an enquiry, customers can contact our customer support team using the contact options provided on the website.

When contacting support regarding an order, customers should provide:

* Their name.
* Order number.
* A brief description of the issue.
* Relevant photographs or supporting information where necessary.

Providing complete information can help us investigate and resolve enquiries more efficiently.

## 15. Changes to This Policy

We may update this Customer Support Policy periodically to reflect changes to our services, AI chatbot functionality, customer support procedures, or legal requirements.

The latest version of the policy will be made available on our website.

**Last Updated: September 2026**
`,
        sourceType: "text",
        sourceId: "customer-support-policy",
        metadata: {
            title: "Customer Support Policy",
            section: "Full Policy",
        },
    }),
});

response.then((res) => res.json())
.then((data) => {
    console.log("Embedding created successfully:", data);
}).then((err) => {
    console.error("Error creating embedding:", err);
});

// import ollama from 'ollama'

// const response = await ollama.embed({
//   model: 'nomic-embed-text',
//   input: 'The sky is blue because of Rayleigh scattering',
// })
// console.log(response.embeddings)
// console.log(response.embeddings[0].length)